--[[
  PWR Reactor Control System - Installer
  Run this on each computer to install the required files.
  
  Usage:
    wget https://raw.githubusercontent.com/brambora69123/OC-PWR-System/main/install.lua install.lua
    install.lua
  
  The installer will detect which components are available and copy
  only the files needed for that computer.
]]

local component = require("component")
local computer  = require("computer")
local fs        = require("filesystem")
local internet  = component.internet

local GITHUB_BASE = "https://raw.githubusercontent.com/brambora69123/OC-PWR-System/main/"

local REACTOR_FILES = {
  "lib/protocol.lua",
  "lib/reactor_ctrl.lua",
  "lib/colors.lua",
  "reactor_server.lua",
}

local CLIENT_FILES = {
  "lib/protocol.lua",
  "lib/reactor_ctrl.lua",
  "lib/colors.lua",
  "lib/gpu2.lua",
  "lib/GUI.lua",
  "lib/advancedLua.lua",
  "lib/doubleBuffering.lua",
  "lib/color.lua",
  "lib/image.lua",
  "lib/unicode.lua",
  "control_client.lua",
  "setup_screens.lua",
}

local function detectType()
  if component.isAvailable("ntm_pwr_control") then
    return "reactor"
  elseif component.isAvailable("gpu") and component.gpu.getDepth() >= 8 then
    return "client"
  end
  return "unknown"
end

local function download(url)
  if not internet then
    return nil, "No internet card"
  end
  local response, err = internet.request(url)
  if not response then
    return nil, err
  end
  local data = ""
  while true do
    local chunk = response.read()
    if not chunk then break end
    data = data .. chunk
  end
  response.close()
  return data
end

local function ensureDir(path)
  local dir = fs.path(path)
  if dir and not fs.exists(dir) then
    fs.makeDirectory(dir)
  end
end

local function installFileList(files, destDir)
  local ok = 0
  local fail = 0
  for _, name in ipairs(files) do
    local fullPath = destDir .. name
    io.write("  " .. name .. "... ")
    ensureDir(fullPath)
    local data, err = download(GITHUB_BASE .. name)
    if data then
      local f = io.open(fullPath, "w")
      if f then
        f:write(data)
        f:close()
        io.write("OK\n")
        ok = ok + 1
      else
        io.write("WRITE FAILED\n")
        fail = fail + 1
      end
    else
      io.write("DOWNLOAD FAILED: " .. tostring(err) .. "\n")
      fail = fail + 1
    end
  end
  return ok, fail
end

local function setupAutorun(compType)
  local script = compType == "reactor" and "reactor_server" or "control_client"
  local autorunPath = "/boot/autorun.lua"
  ensureDir(autorunPath)
  local f = io.open(autorunPath, "w")
  if not f then
    print("WARNING: Could not create " .. autorunPath)
    return false
  end
  f:write("-- Auto-generated by PWR Reactor Control System installer\n")
  f:write("-- Starts " .. script .. " on boot\n")
  f:write("local ok, err = pcall(dofile, \"/home/" .. script .. ".lua\")\n")
  f:write("if not ok then\n")
  f:write("  print('[PWR] Failed to start: ' .. tostring(err))\n")
  f:write("end\n")
  f:close()
  print("Autorun installed: " .. autorunPath .. " -> " .. script)
  return true
end

local function main()
  print("========================================")
  print("  PWR Reactor Control System Installer")
  print("========================================")
  print()

  if not internet then
    print("ERROR: No internet card found!")
    print("Insert an internet card and try again.")
    return
  end

  local compType = detectType()
  print("Detected: " .. compType)

  if compType == "unknown" then
    print()
    print("Could not auto-detect. Select:")
    print("  [1] Reactor PC")
    print("  [2] Control Room PC")
    io.write("Choice: ")
    local choice = io.read()
    if choice == "1" then compType = "reactor"
    elseif choice == "2" then compType = "client"
    else print("Invalid."); return end
  end

  print()
  if compType == "reactor" then
    print("Installing REACTOR files to /home/ ...")
    local ok, fail = installFileList(REACTOR_FILES, "/home/")
    print("Done. " .. ok .. " OK, " .. fail .. " failed.")
  else
    print("Installing CONTROL ROOM files...")
    print("  Libraries -> /lib/")
    local ok1, fail1 = installFileList({
      "lib/protocol.lua", "lib/reactor_ctrl.lua", "lib/colors.lua",
      "lib/gpu2.lua", "lib/GUI.lua", "lib/advancedLua.lua",
      "lib/doubleBuffering.lua", "lib/color.lua", "lib/image.lua", "lib/unicode.lua",
    }, "/")
    print("  Scripts -> /home/")
    local ok2, fail2 = installFileList({
      "control_client.lua", "setup_screens.lua",
    }, "/home/")
    print("Done. " .. (ok1+ok2) .. " OK, " .. (fail1+fail2) .. " failed.")
  end

  print()
  io.write("Install autorun on boot? [Y/n]: ")
  local choice = io.read()
  if not choice or choice:lower() ~= "n" then
    setupAutorun(compType)
  end

  print()
  if compType == "reactor" then
    print("Run: reactor_server")
  else
    print("Run: setup_screens (once), then: control_client")
  end
  print("To disable autorun: rm /boot/autorun.lua")
end

main()
