--[[
  PWR Reactor Control System - Installer v2.2
  Installs all files to /home/pwr/
  
  Usage:
    wget https://raw.githubusercontent.com/brambora69123/OC-PWR-System/main/install.lua install.lua
    install.lua
  
  Requires: OpenOS, Network Card (wireless)
]]

local component = require("component")
local fs        = require("filesystem")
local shell     = require("shell")

local BASE = "https://raw.githubusercontent.com/brambora69123/OC-PWR-System/main/"
local DIR  = "/home/pwr"
local LIB  = DIR .. "/lib"

-- Files to download: {repo_path, local_dir, local_name}
local LIB_FILES = {
  {"lib/protocol.lua",     LIB, "protocol.lua"},
  {"lib/reactor_ctrl.lua", LIB, "reactor_ctrl.lua"},
  {"lib/colors.lua",       LIB, "colors.lua"},
  {"lib/gpu2.lua",         LIB, "gpu2.lua"},
}

local REACTOR_FILES = {
  {"reactor_server.lua", DIR, "reactor_server.lua"},
}

local CLIENT_FILES = {
  {"control_client.lua", DIR, "control_client.lua"},
  {"setup_screens.lua",  DIR, "setup_screens.lua"},
}

local function detectType()
  if component.isAvailable("ntm_pwr_control") then return "reactor" end
  if component.isAvailable("gpu") and component.gpu.getDepth() >= 8 then return "client" end
  return "unknown"
end

local function ensureDir(path)
  local dir = fs.path(path)
  if dir and not fs.exists(dir) then fs.makeDirectory(dir) end
end

local function download(urlPath, localDir, localName)
  local url = BASE .. urlPath
  local fullPath = localDir .. "/" .. localName
  ensureDir(fullPath)
  local cmd = string.format('cd %s && wget -fq "%s" "%s"', localDir, url, localName)
  local ok, err = shell.execute(cmd)
  return ok
end

local function installFiles(files)
  local ok, fail = 0, 0
  for _, f in ipairs(files) do
    local urlPath, localDir, localName = f[1], f[2], f[3]
    io.write("  " .. localDir .. "/" .. localName .. " ... ")
    if download(urlPath, localDir, localName) then
      io.write("OK\n")
      ok = ok + 1
    else
      io.write("FAILED\n")
      fail = fail + 1
    end
  end
  return ok, fail
end

local function setupAutorun(compType)
  local script = compType == "reactor" and "reactor_server" or "control_client"
  local path = "/home/.pwr_autorun"
  local f = io.open(path, "w")
  if not f then
    print("WARNING: Could not create " .. path)
    return false
  end
  f:write("-- Auto-generated by PWR Reactor Control System installer\n")
  f:write("local ok, err = pcall(dofile, \"" .. DIR .. "/" .. script .. ".lua\")\n")
  f:write("if not ok then print(\"[PWR] \" .. tostring(err)) end\n")
  f:close()
  print("Autorun: " .. path .. " -> " .. script)
  return true
end

local function main()
  print("========================================")
  print("  PWR Reactor Control System v2.2")
  print("========================================\n")

  -- Note about wireless
  print("NOTE: Both computers need a Network Card (wireless).")
  print("      The modem is wireless by default in OpenComputers.\n")

  -- Detect type
  local compType = detectType()
  print("Detected: " .. compType)

  if compType == "unknown" then
    print("\nSelect install type:")
    print("  [1] Reactor PC  (next to the reactor)")
    print("  [2] Control Room PC (2x GPU + 2x Screen)")
    io.write("Choice: ")
    local c = io.read()
    if c == "1" then compType = "reactor"
    elseif c == "2" then compType = "client"
    else print("Invalid choice."); return end
  end

  -- Create directories
  ensureDir(LIB .. "/dummy")

  -- Install libs (needed by both)
  print("\nInstalling libraries...")
  local ok, fail = installFiles(LIB_FILES)

  -- Install main scripts
  local mainFiles = compType == "reactor" and REACTOR_FILES or CLIENT_FILES
  print("\nInstalling " .. compType .. " files...")
  local ok2, fail2 = installFiles(mainFiles)

  local totalOk = ok + ok2
  local totalFail = fail + fail2

  print(string.format("\nDone: %d OK, %d failed", totalOk, totalFail))

  if totalFail > 0 then
    print("\nSome files failed to download.")
    print("Check your network card is installed and try again.")
    return
  end

  -- Autorun
  print()
  io.write("Install autorun on boot? [Y/n]: ")
  local c = io.read()
  if not c or c:lower() ~= "n" then
    setupAutorun(compType)
  end

  -- Post-install instructions
  print()
  print("=" .. string.rep("=", 40))
  if compType == "reactor" then
    print("Reactor PC installed!")
    print()
    print("  Run: " .. DIR .. "/reactor_server.lua")
  else
    print("Control Room PC installed!")
    print()
    print("  First: " .. DIR .. "/setup_screens.lua")
    print("  Then:  " .. DIR .. "/control_client.lua")
  end
  print()
  print("To disable autorun:")
  print("  rm /home/.pwr_autorun")
  print("=" .. string.rep("=", 40))
end

main()
